#!/usr/bin/env bash

declare -x POSTGRESQL_ROOT_PASSWORD
: "${POSTGRESQL_ROOT_PASSWORD:=""}"

declare -x POSTGRESQL_USERNAME
: "${POSTGRESQL_USERNAME:=""}"

declare -x POSTGRESQL_PASSWORD
: "${POSTGRESQL_PASSWORD:="${POSTGRESQL_ROOT_PASSWORD}"}"

declare -x POSTGRESQL_DATABASE
: "${POSTGRESQL_DATABASE:="${POSTGRESQL_USERNAME}"}"

declare -x POSTGRESQL_MAX_CONNECTIONS
: "${POSTGRESQL_MAX_CONNECTIONS:="100"}"

declare -x POSTGRESQL_SUPERUSER_CONNECTIONS
: "${POSTGRESQL_SUPERUSER_CONNECTIONS:="3"}"

declare -x POSTGRESQL_AUTH_METHOD
: "${POSTGRESQL_AUTH_METHOD:="md5"}"

declare -x POSTGRESQL_INITDB_LOCALE
: "${POSTGRESQL_INITDB_LOCALE:="en_US.UTF-8"}"

declare -x POSTGRESQL_ADDITIONAL_HBA
: "${POSTGRESQL_ADDITIONAL_HBA:=""}"

declare -x POSTGRESQL_ADDITIONAL_IDENT
: "${POSTGRESQL_ADDITIONAL_IDENT:=""}"

declare -x POSTGRESQL_SKIP_MKDIR
: "${POSTGRESQL_SKIP_MKDIR:="false"}"

declare -x POSTGRESQL_SKIP_CHMOD
: "${POSTGRESQL_SKIP_CHMOD:="false"}"

declare -x POSTGRESQL_SKIP_CHOWN
: "${POSTGRESQL_SKIP_CHOWN:="false"}"
