#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

STARTCMD="su-exec postgres /usr/bin/postgres -D /etc/postgresql"

if [ ! -f "/var/lib/postgresql/PG_VERSION" ]
then
  if [ -z "${POSTGRESQL_ROOT_PASSWORD}" ]
  then
    echo >&2 "Error: Database is uninitialized and POSTGRESQL_ROOT_PASSWORD not set"
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi

  echo "Running initdb..."
  su-exec postgres initdb --username=postgres --pgdata=/var/lib/postgresql --locale=${POSTGRESQL_INITDB_LOCALE}

  echo "Locally start..."
  su-exec postgres pg_ctl -D /etc/postgresql -o "-c listen_addresses='localhost'" -w start

  psql=(psql -v ON_ERROR_STOP=1)

  echo "Setting password..."
  "${psql[@]}" --username postgres -c "ALTER USER postgres WITH SUPERUSER PASSWORD '${POSTGRESQL_ROOT_PASSWORD}';"

  if [ -n "${POSTGRESQL_DATABASE}" ]
  then
    if [[ "${POSTGRESQL_DATABASE}" != "postgres" ]]
    then
      echo "Creating database..."
      "${psql[@]}" --username postgres -c "CREATE DATABASE "${POSTGRESQL_DATABASE}";"
    fi

    if [ -n "${POSTGRESQL_USERNAME}" ]
    then
      echo "Creating user..."
      "${psql[@]}" --username postgres -c "CREATE USER ${POSTGRESQL_USERNAME} WITH SUPERUSER PASSWORD '${POSTGRESQL_PASSWORD}';"
    fi
  fi

  echo "Locally stop..."
  su-exec postgres pg_ctl -D /etc/postgresql -m fast -w stop
fi

echo "Starting PostgreSQL daemon..."
exec ${STARTCMD}
