FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:1e14dc19caca0a87e98fb6066851712c4bfc9bcd9202ce6598161eb6d1b8bfff

VOLUME ["/var/lib/postgresql", "/var/lib/backup", "/etc/postgresql/init.d", "/etc/postgresql/conf.d"]
EXPOSE 5432

WORKDIR /var/lib/postgresql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  groupadd -g 1000 postgresql && \
  useradd -u 1000 -d /var/lib/postgresql -g postgresql -s /bin/bash -m postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/* /etc/postgresql

COPY ./overlay /
