FROM ghcr.io/dockhippie/alpine:3.23-arm@sha256:d0a1ef356bc132e6883c45ffd98e9e29bdddd45ce6580062828e3e3107c37d0a

VOLUME ["/var/lib/postgresql", "/var/lib/backup", "/etc/postgresql/init.d", "/etc/postgresql/conf.d"]
EXPOSE 5432

WORKDIR /var/lib/postgresql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  groupadd -g 1000 postgresql && \
  useradd -u 1000 -d /var/lib/postgresql -g postgresql -s /bin/bash -m postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/* /etc/postgresql

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/backup /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/backup /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
