FROM webhippie/alpine:latest-arm32v6@sha256:f52146000ae31a8e6df968e3ab3680f5d799b1e5cb2100fa90ec71584068b0a7

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="PostgreSQL" \
  org.label-schema.vcs-url="https://github.com/dockhippie/pstgresql.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5432

VOLUME ["/var/lib/postgresql", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/*

COPY ./overlay ./overlay-arm32v6 /
