FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:0e957df399b45a95a1f84e781a69f6001de57ac609855f412a8b90e02603d18f

VOLUME ["/var/lib/postgresql", "/var/lib/backup", "/etc/postgresql/init.d", "/etc/postgresql/conf.d"]
EXPOSE 5432

WORKDIR /var/lib/postgresql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  groupadd -g 1000 postgresql && \
  useradd -u 1000 -d /var/lib/postgresql -g postgresql -s /bin/bash -m postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/* /etc/postgresql

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/backup /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/backup /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
