FROM webhippie/alpine:latest@sha256:9e1997e04f7fa611f8c114b66ef5c23c7624f890522c1420c3a7f06ddf7ca294

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="PostgreSQL" \
  org.label-schema.vcs-url="https://github.com/dockhippie/pstgresql.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5432

VOLUME ["/var/lib/postgresql", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/*

COPY ./overlay ./overlay-amd64 /
