FROM ghcr.io/dockhippie/alpine:3.23-arm@sha256:665f73afb023945dfaa06dee1b751f34647c2d2cd99192ae28602c9687b92d6b

VOLUME ["/var/lib/postgresql", "/var/lib/backup", "/etc/postgresql/init.d", "/etc/postgresql/conf.d"]
EXPOSE 5432

WORKDIR /var/lib/postgresql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  groupadd -g 1000 postgresql && \
  useradd -u 1000 -d /var/lib/postgresql -g postgresql -s /bin/bash -m postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/* /etc/postgresql

COPY ./overlay /
