FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:d7813fe27f3eeb726a418182751235f564ab8e965cc6e35d6f676fba29ee05bd

VOLUME ["/var/lib/postgresql", "/var/lib/backup", "/etc/postgresql/init.d", "/etc/postgresql/conf.d"]
EXPOSE 5432

WORKDIR /var/lib/postgresql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  groupadd -g 1000 postgresql && \
  useradd -u 1000 -d /var/lib/postgresql -g postgresql -s /bin/bash -m postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/* /etc/postgresql

COPY ./overlay /
