FROM webhippie/alpine:3.22-amd64@sha256:bad260a7ba50413aa2eb93905869aade5b5db9fd33ad86d7fde851f3993b8cee

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="PostgreSQL" \
  org.label-schema.version="latest" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5432

VOLUME ["/var/lib/postgresql", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/*

COPY ./overlay ./overlay-amd64 /
