FROM webhippie/alpine:3.22-amd64@sha256:504d458afc87b8775f66c3bf2c632429dcd7a25097a1f64494a2530ff3637bc6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="PostgreSQL" \
  org.label-schema.version="latest" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5432

VOLUME ["/var/lib/postgresql", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/*

COPY ./overlay ./overlay-amd64 /
