FROM webhippie/alpine:3.22-amd64@sha256:5697b876ee0a0c0fc7a4e1b8302c3ae2c937591e3079aa62d084490b24f43498

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="PostgreSQL" \
  org.label-schema.version="latest" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5432

VOLUME ["/var/lib/postgresql", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/postgresql && \
  apk add postgresql postgresql-client postgresql-contrib && \
  rm -rf /var/cache/apk/* /var/lib/postgresql/*

COPY ./overlay ./overlay-amd64 /
